import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {AuthHydration} from "@/components/layout/auth-hydration.component";

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <AuthHydration/>
        <body
            className={`${poppins.className}  antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
