version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    ports:
      - "5432:5432"  # host:container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - db
    command:
        npm run start:dev
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command:
      npm run dev
    restart: unless-stopped
    
volumes:
  pgdata:
  redis-data:
