import type {Metadata} from "next";
import {ReactNode} from "react";
import DialDetails from "@/components/ui/dial-details";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DialsLayout({children}:{children: ReactNode}) {
    return (
        <div className="flex min-h-screen p-4 gap-4">
            <div className="w-full">{children}</div>
            <div className="w-1/2">
                <DialDetails />
            </div>
        </div>
    )
        ;
}
